package com.ane.realtime.bean

import java.math.BigDecimal


/**
  * @description 实际表数据实体类
  * @author zhangleilei
  * @create 2020/11/5
  */
case class ActualLoadUnloadResultBean(
                                       version: Int,
                                       waybillNo: String,
                                       subBillNo: String,
                                       goodsWeight: BigDecimal,
                                       calcWeight: BigDecimal,
                                       operateWeight: BigDecimal,
                                       goodsVolume: BigDecimal,
                                       piece: Int,
                                       ticket: Int,
                                       productType: String,
                                       lengthOfTime: String,
                                       mustGoGoods: String,
                                       superiorityProduct: String,
                                       areaType: String,
                                       remark: String,
                                       trackLine: String,
                                       taskNo: String,
                                       transportLineType: String,
                                       deliveryReceiptNo: String,
                                       carNo: String,
                                       carType: String,
                                       isOriginCenter: String,
                                       isDestinationCenter: String,
                                       routePath: String,
                                       scanGoodsDepartureTime: String,
                                       scanTime: String,
                                       scanType: String,
                                       scanSite: String,
                                       scanSiteCode: String,
                                       scanArea: String,
                                       scanBigArea: String,
                                       scanProvinceArea: String,
                                       scanRegion: String,
                                       scanProvince: String,
                                       scanCity: String,
                                       scanCounty: String,
                                       scanLongitude: String,
                                       scanLatitude: String,
                                       preSite: String,
                                       preSiteCode: String,
                                       preArea: String,
                                       preBigArea: String,
                                       preProvinceArea: String,
                                       preRegion: String,
                                       preProvince: String,
                                       preCity: String,
                                       preCounty: String,
                                       preLongitude: String,
                                       preLatitude: String,
                                       nextSite: String,
                                       nextSiteCode: String,
                                       nextArea: String,
                                       nextBigArea: String,
                                       nextProvinceArea: String,
                                       nextRegion: String,
                                       nextProvince: String,
                                       nextCity: String,
                                       nextCounty: String,
                                       nextLongitude: String,
                                       nextLatitude: String,
                                       originSite: String,
                                       originSiteCode: String,
                                       originArea: String,
                                       originBigArea: String,
                                       originProvinceArea: String,
                                       originRegion: String,
                                       originProvince: String,
                                       originCity: String,
                                       originCounty: String,
                                       originLongitude: String,
                                       originLatitude: String,
                                       originCenter: String,
                                       originCenterCode: String,
                                       destinationCenter: String,
                                       destinationCenterCode: String,
                                       destinationSite: String,
                                       destinationSiteCode: String,
                                       destinationArea: String,
                                       destinationBigArea: String,
                                       destinationProvinceArea: String,
                                       destinationRegion: String,
                                       destinationProvince: String,
                                       destinationCity: String,
                                       destinationCounty: String,
                                       destinationLongitude: String,
                                       destinationLatitude: String,
                                       currentSystemTime: String,
                                       aggregateIndexTime: String

                                     )


