package com.ane.realtime.bean

/**
  * @description 预测表数据实体类
  * @author zhangleilei
  * @create 2020/11/5
  */
case class RoutePlanResultBean(
                                       waybillNo: String,
                                       subBillNo: String,
                                       goodsWeight: Double,
                                       calcWeight: Double,
                                       operateWeight: Double,
                                       goodsVolume: Double,
                                       piece: String,
                                       ticket: String,
                                       productType: String,
                                       lengthOfTime: String,
                                       mustGoGoods: String,
                                       superiorityProduct: String,
                                       areaType: String,
                                       remark: String,
                                       trackLine: String,
                                       taskNo: String,
                                       transportLineType: String,
                                       deliveryReceiptNo: String,
                                       carNo: String,
                                       carType: String,
                                       isOriginCenter: String,
                                       isDestinationCenter: String,
                                       routePath: String,
                                       scanGoodsDepartureTime: String,
                                       scanTime: String,
                                       scanType: String,
                                       scanSite: String,
                                       scanSiteCode: String,
                                       scanArea: String,
                                       scanBigArea: String,
                                       scanProvinceArea: String,
                                       scanRegion: String,
                                       scanProvince: String,
                                       scanCity: String,
                                       scanCounty: String,
                                       preSite: String,
                                       preSiteCode: String,
                                       preArea: String,
                                       preBigArea: String,
                                       preProvinceArea: String,
                                       preRegion: String,
                                       preProvince: String,
                                       preCity: String,
                                       preCounty: String,
                                       nextSite: String,
                                       nextSiteCode: String,
                                       nextArea: String,
                                       nextBigArea: String,
                                       nextProvinceArea: String,
                                       nextRegion: String,
                                       nextProvince: String,
                                       nextCity: String,
                                       nextCounty: String,
                                       originSite: String,
                                       originSiteCode: String,
                                       originArea: String,
                                       originBigArea: String,
                                       originProvinceArea: String,
                                       originRegion: String,
                                       originProvince: String,
                                       originCity: String,
                                       originCounty: String,
                                       destinationSite: String,
                                       destinationSiteCode: String,
                                       destinationArea: String,
                                       destinationBigArea: String,
                                       destinationProvinceArea: String,
                                       destinationRegion: String,
                                       destinationProvince: String,
                                       destinationCity: String,
                                       destinationCounty: String
                                     )


